### ISSUE TITLE
TypeError: plotting not available

### ISSUE THREAD

**Issue by Billy1900** [duxiaoqin/VGAE#1]
When I run the code with Python version 3.7, tf 1.14, the error occurred, the stack trace is below.
<pre>
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main()
  File "main.py", line 27, in main
    coo_adjacency, edges = GraphReader.GetGraphCluster(common.DatasetFile)
  File "C:\Users\PC\Desktop\VGAE-master\GraphReader.py", line 55, in GetGraphCluster
    ig.plot(G)
  File "D:\Anaconda\envs\tf14\lib\site-packages\igraph\drawing\__init__.py", line 455, in plot
    result = Plot(target, bbox, background=kwds.get("background", "white"))
  File "D:\Anaconda\envs\tf14\lib\site-packages\igraph\drawing\__init__.py", line 120, in __init__
    self._surface_was_created = not isinstance(target, cairo.Surface)
  File "D:\Anaconda\envs\tf14\lib\site-packages\igraph\drawing\utils.py", line 396, in __getattr__
    raise TypeError("plotting not available")
TypeError: plotting not available
</pre>

**Comment by duxiaoqin** [comment]
Thank you! 
Please install python-igraph & pycairo packages. For example, in Windows, you can download these similar files (for your running environment) and install them:
pip install python_igraph-0.7.1.post6-cp35-cp35m-win_amd64.whl
pip install pycairo-1.18.1-cp35-cp35m-win_amd64.whl

**Comment by Billy1900** [comment]
thanks a lot for your help.
